### ISSUE TITLE
有个问题请教一下

### ISSUE THREAD

**Issue by ghost** [yoxisem544/Moya-RxSwift-Decodable#1]
Hello,

拜读了你的代码，有个问题请教一下：

如果服务器返回的是下面形式的数据（用户列表，有分页数据）：
`{
  limit: 10,
  offset: 0,
  total: 100,
  users: [
    {},
    {},
    ...
  ] 
}`

如果在具体的 TargetType 中指定了：`typealias ResponseType = [User]`，那通过`.map(Request.ResponseType.self) ` 最终获得 users 数据。这个没问题。

我的问题是：如果使用你的设计思路，如何在最后的 onSuccess 还能获取到 total 信息呢？像这种情况，怎么处理比较好？

感谢 🙏

**Comment by yoxisem544** [comment]
服务器返回的数据常是你说的
`{ limit: 10, offset: 0, total: 100, users: [ {}, {}, ... ] }`
形式

但 total 信息常常也是我们判断 users 总量的一个依据，在这个情况下我会写一个用户列表回应数据
像是：
```swift
struct UserListResponse: Decodable {
  let limit: Int
  let offset: Int
  let total: Int
  let users: [User]

  enum CodingKeys: String, CodingKey {
    // possible keys....
  }

  init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    // decode for total/limit/offset values
    users = try container.decode([User].self, forKey: .xxxxKey)
  }
}
```

如此一来，只要在 `typealias ResponseType = UserListResponse` 这样写，即可获得 `total` 数据
```swift
response.total // 取得 total 数据
response.users // 取得 users 数据
```

这是使用 `Decodable` 比较不方便的地方，遇到朝状结构的 JSON 就要一层一层写，不如 SwiftyJSON/Unbox/ObjectMapper 方便。

关于 `Decodable` 更详细的介绍，欢迎参照 https://benscheirman.com/2017/06/swift-json/。

有其他问题欢迎在底下留言讨论 :)

**Comment by ghost** [comment]
@yoxisem544 非常感谢。用 struct 替代 enum 做 target 的思路非常棒 👍 

还有个 moya 相关的问题请教：
当前页面回退到上一页（navigation），而当前页面的请求还没有返回，我们是否需要去当前页面的 deinit 中去手动 cancel 这个 request ? 如果不 cancel 会不会出问题？

**Comment by yoxisem544** [comment]
会建议在退回上一个页面时，将前一个页面的所有请求都 cancel 掉，避免浪费资源。

但不管有没有 cancel 掉 request，都要注意 rx chain 中引用 self 时要使用 weak reference 引用，避免 rx block 循环引用 self 而造成 memory leak。

**Comment by yoxisem544** [comment]
我自己有时候比较偏爱 PromiseKit，自己也写了一些扩展：
https://gist.github.com/yoxisem544/f2a42087637f8d630b93bef8765281a9

**Comment by ghost** [comment]
@yoxisem544 「网络缓存」你一般是怎么设计（实现）的，能简单说两句吗？
用 NSURLCache，还是？

**Comment by yoxisem544** [comment]
这就要看你状况而定了，也不是简单两句可以说完的

**Comment by ghost** [comment]
问题提的不好。添麻烦了。
